/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author edgar
 */
public class FrmSrlrccionTelas extends javax.swing.JFrame {

    /**
     * Creates new form FrmSrlrccionTelas
     */
    public FrmSrlrccionTelas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextTela = new javax.swing.JTextField();
        jTextTelaPantalon = new javax.swing.JTextField();
        jTextTelaPlayera = new javax.swing.JTextField();
        jTextTelaCamisa = new javax.swing.JTextField();
        jTextTelaSudadera = new javax.swing.JTextField();
        jBtnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(202, 250, 238));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1050, 630));
        jPanel2.setMinimumSize(new java.awt.Dimension(1050, 630));
        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextTela.setEditable(false);
        jTextTela.setBackground(new java.awt.Color(0, 0, 204));
        jTextTela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextTela.setForeground(new java.awt.Color(255, 255, 255));
        jTextTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTela.setText("Tipo de tela disponibles en el sistema");
        jTextTela.setToolTipText("");
        jTextTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 60));

        jTextTelaPantalon.setEditable(false);
        jTextTelaPantalon.setBackground(new java.awt.Color(204, 204, 255));
        jTextTelaPantalon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextTelaPantalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelaPantalon.setText("Algodon");
        jTextTelaPantalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaPantalonActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, 80));

        jTextTelaPlayera.setEditable(false);
        jTextTelaPlayera.setBackground(new java.awt.Color(102, 102, 255));
        jTextTelaPlayera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextTelaPlayera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelaPlayera.setText("Lino");
        jTextTelaPlayera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaPlayeraActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelaPlayera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 510, 80));

        jTextTelaCamisa.setEditable(false);
        jTextTelaCamisa.setBackground(new java.awt.Color(204, 204, 255));
        jTextTelaCamisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextTelaCamisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelaCamisa.setText("Poliester");
        jTextTelaCamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaCamisaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelaCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 510, 80));

        jTextTelaSudadera.setEditable(false);
        jTextTelaSudadera.setBackground(new java.awt.Color(102, 102, 255));
        jTextTelaSudadera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextTelaSudadera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelaSudadera.setText("Mezclilla");
        jTextTelaSudadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaSudaderaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelaSudadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 510, 80));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 510, 380));

        jBtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/btnRegresar.png"))); // NOI18N
        jBtnExit.setBorder(null);
        jBtnExit.setContentAreaFilled(false);
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesUser/logo_proyecto (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAdmin/TiposTelaLogo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 520, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/mc_sup_derecha.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAdmin/mc_sup.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1270, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/mc_derecha.png"))); // NOI18N
        jLabel2.setText(" ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        FrmAdmin admin = new FrmAdmin();
        admin.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jTextTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaActionPerformed

    private void jTextTelaPantalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaPantalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaPantalonActionPerformed

    private void jTextTelaPlayeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaPlayeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaPlayeraActionPerformed

    private void jTextTelaCamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaCamisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaCamisaActionPerformed

    private void jTextTelaSudaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaSudaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaSudaderaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSrlrccionTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSrlrccionTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSrlrccionTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSrlrccionTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSrlrccionTelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField jTextTela;
    public javax.swing.JTextField jTextTelaCamisa;
    public javax.swing.JTextField jTextTelaPantalon;
    public javax.swing.JTextField jTextTelaPlayera;
    public javax.swing.JTextField jTextTelaSudadera;
    // End of variables declaration//GEN-END:variables
}
